# Generated by Django 5.0.7 on 2025-10-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0003_delete_group_delete_student_entry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='entries/', verbose_name='Изображение'),
        ),
    ]
